#!/usr/bin/env php
<?php

use Twitsup\Ports\Cli\TwitsupApplicationConfig;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/app/container.php';

$cli = new ConsoleApplication(new TwitsupApplicationConfig($container));
$cli->run();
